[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "trafiklab-sl"
version = "0.1.2"
description = "Storstockholms Lokaltrafik (SL) data via Trafiklab API"
readme = "README.md"
requires-python = ">=3.9.0"
license = { file = "LICENSE.txt" }
keywords = ["SL", "Storstockholms Lokaltrafik", "Trafiklab"]
authors = [
    {name="Mikalai Kukhta", email="mikalai.kukhta@gmail.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
    "aiohttp",
    "dataclasses_json",
]

[project.urls]
Repository = "https://github.com/NecroKote/trafiklab-sl"
Issues = "https://github.com/NecroKote/trafiklab-sl/issues"

[project.optional-dependencies]
dev = [
    "wheel",
    "build",
    "twine",
    "tox",
]
test = [
    "pytest==8.0.0",
    "pytest-asyncio==0.23.5",
]

[tool.setuptools.packages.find]
exclude = ["tests*"]
namespaces = false

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.tox]
legacy_tox_ini = """
    [tox]
    minversion = 4.14.0
    envlist = py39,py310,py311,py312

    [testenv]
    deps =
        pytest==8.0.0
        pytest-asyncio==0.23.5

    commands = pytest -s tests --integration
"""
