name: test

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
      - name: Install tox
        run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv --with tox-gh
      - name: Setup test suite
        run: tox run -vv --notest --skip-missing-interpreters false
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.python-version }}
      - name: Run test suite
        run: tox run --skip-pkg-install
        env:
          SL_LOOKUP_API_KEY: ${{ secrets.SL_LOOKUP_API_KEY }}
          TOX_GH_MAJOR_MINOR: ${{ matrix.python-version }}
